#!/bin/bash
# Script de configuración para proteger la rama Variation1 en GitHub

echo "═══════════════════════════════════════════════════════════════════"
echo "PROTEGER RAMA VARIATION1 EN GITHUB"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "La rama Variation1 ha sido subida al repositorio remoto."
echo ""
echo "Para protegerla, sigue estos pasos en GitHub:"
echo ""
echo "1. Ve a: https://github.com/DarkyGr/CETES---Calculadora"
echo ""
echo "2. Haz clic en: Settings (Configuración)"
echo ""
echo "3. En el menú lateral, busca: Branches (Ramas)"
echo ""
echo "4. Bajo 'Branch protection rules' (Reglas de protección de rama)"
echo "   Haz clic en: 'Add rule' (Agregar regla)"
echo ""
echo "5. En 'Branch name pattern' (Patrón de nombre de rama):"
echo "   Escribe: Variation1"
echo ""
echo "6. Habilita las siguientes opciones:"
echo "   ☑ Require a pull request before merging"
echo "     └─ Require approvals: 1"
echo ""
echo "   ☑ Require status checks to pass before merging"
echo "     └─ Require branches to be up to date before merging"
echo ""
echo "   ☑ Restrict who can push to matching branches"
echo "     └─ Selecciona: Solo maintainers"
echo ""
echo "   ☑ Allow force pushes: Deshabilitado"
echo ""
echo "   ☑ Allow deletions: Deshabilitado"
echo ""
echo "7. Haz clic en: 'Create' (Crear)"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "INFORMACIÓN DE COMMITS:"
echo "═══════════════════════════════════════════════════════════════════"
echo ""

cd "$(dirname "$0")"

echo "Rama actual:"
git branch --show-current
echo ""

echo "Últimos 2 commits:"
git log --oneline -2
echo ""

echo "Archivos en Variation1 (respecto a main):"
git diff main..Variation1 --name-status
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "✅ RAMA SUBIDA AL REPOSITORIO REMOTO"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "URL de Pull Request:"
echo "https://github.com/DarkyGr/CETES---Calculadora/pull/new/Variation1"
echo ""
echo "Estado actual:"
echo "✅ Rama creada localmente"
echo "✅ Cambios commiteados"
echo "✅ Subida al repositorio remoto"
echo "⏳ Pendiente: Configurar protección en GitHub"
echo "⏳ Pendiente: Crear Pull Request"
echo "⏳ Pendiente: Revisión de código"
echo ""
